# Generated by Django 3.2.8 on 2021-10-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('InstructorID', models.AutoField(primary_key=True, serialize=False)),
                ('InstructorName', models.CharField(max_length=255)),
            ],
        ),
    ]
