export const SYS_LEARNER_REQUEST = 'SYS_LEARNER_REQUEST'
export const SYS_LEARNER_SUCCESS = 'SYS_LEARNER_SUCCESS'
export const SYS_LEARNER_FAIL = 'SYS_LEARNER_FAIL'


export const SYS_INS_REQUEST = 'SYS_INS_REQUEST'
export const SYS_INS_SUCCESS = 'SYS_INS_SUCCESS'
export const SYS_INS_FAIL = 'SYS_INS_FAIL'