export const CONVERSATION_SENDER_LIST_REQUEST = "CONVERSATION_SENDER_LIST_REQUEST";
export const CONVERSATION_SENDER_LIST_SUCCESS = "CONVERSATION_SENDER_LIST_SUCCESS";
export const CONVERSATION_SENDER_LIST_FAIL = "CONVERSATION_SENDER_LIST_FAIL";

export const CONVERSATION_RCV_LIST_REQUEST = "CONVERSATION_RCV_LIST_REQUEST";
export const CONVERSATION_RCV_LIST_SUCCESS = "CONVERSATION_RCV_LIST_SUCCESS";
export const CONVERSATION_RCV_LIST_FAIL = "CONVERSATION_RCV_LIST_FAIL";
