export const CREATE_CVS_REQUEST = "CREATE_CVS_REQUEST"
export const CREATE_CVS_SUCCESS = "CREATE_CVS_SUCCESS"
export const CREATE_CVS_FAIL = "CREATE_CVS_FAIL"

export const GET_SEND_CVS_REQUEST = "GET_SEND_CVS_REQUEST"
export const GET_SEND_CVS_SUCCESS = "GET_SEND_CVS_SUCCESS"
export const GET_SEND_CVS_FAIL = "GET_SEND_CVS_FAIL"

export const GET_RECEIVE_CVS_REQUEST = "GET_RECEIVE_CVS_REQUEST"
export const GET_RECEIVE_CVS_SUCCESS = "GET_RECEIVE_CVS_SUCCESS"
export const GET_RECEIVE_CVS_FAIL = "GET_RECEIVE_CVS_FAIL"

