export const CONVERSATION_LIST_REQUEST = "CONVERSATION_LIST_REQUEST";
export const CONVERSATION_LIST_SUCCESS = "CONVERSATION_LIST_SUCCESS";
export const CONVERSATION_LIST_FAIL = "CONVERSATION_LIST_FAIL";
