export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST'
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS'
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL'


export const COURSE_DETAIL_REQUEST = 'COURSE_DETAIL_REQUEST'
export const COURSE_DETAIL_SUCCESS = 'COURSE_DETAIL_SUCCESS'
export const COURSE_DETAIL_FAIL = 'COURSE_DETAIL_FAIL'

export const COURSE_DETAIL_RATE_REQUEST = 'COURSE_DETAIL_RATE_REQUEST'
export const COURSE_DETAIL_RATE_SUCCESS = 'COURSE_DETAIL_RATE_SUCCESS'
export const COURSE_DETAIL_RATE_FAIL = 'COURSE_DETAIL_RATE_FAIL'

export const COURSE_CREATE_REVIEW_REQUEST = 'COURSE_CREATE_REVIEW_REQUEST'
export const COURSE_CREATE_REVIEW_SUCCESS = 'COURSE_CREATE_REVIEW_SUCCESS'
export const COURSE_CREATE_REVIEW_FAIL = 'COURSE_CREATE_REVIEW_FAIL'
export const COURSE_CREATE_REVIEW_RESET = 'COURSE_CREATE_REVIEW_RESET'