export const LESSON_LIST_REQUEST = 'LESSON_LIST_REQUEST'
export const LESSON_LIST_SUCCESS = 'LESSON_LIST_SUCCESS'
export const LESSON_LIST_FAIL = 'LESSON_LIST_FAIL'


export const LESSON_DETAIL_REQUEST = 'LESSON_DETAIL_REQUEST'
export const LESSON_DETAIL_SUCCESS = 'LESSON_DETAIL_SUCCESS'
export const LESSON_DETAIL_FAIL = 'LESSON_DETAIL_FAIL'

export const CREATE_LESSON_REQUEST = 'CREATE_LESSON_REQUEST'
export const CREATE_LESSON_SUCCESS = 'CREATE_LESSON_SUCCESS'
export const CREATE_LESSON_FAIL = 'CREATE_LESSON_FAIL'