export const MY_COURSE_REQUEST = 'MY_COURSE_REQUEST'
export const MY_COURSE_SUCCESS = 'MY_COURSE_SUCCESS'
export const MY_COURSE_FAIL = 'MY_COURSE_FAIL'

export const ADD_COURSE_REQUEST = 'ADD_COURSE_REQUEST'
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS'
export const ADD_COURSE_FAIL = 'ADD_COURSE_FAIL'

export const MY_ONE_COURSE_REQUEST = 'MY_ONE_COURSE_REQUEST'
export const MY_ONE_COURSE_SUCCESS = 'MY_ONE_COURSE_SUCCESS'
export const MY_ONE_COURSE_FAIL = 'MY_ONE_COURSE_FAIL'

export const ENROLL_COURSE_REQUEST = 'ENROLL_COURSE_REQUEST'
export const ENROLL_COURSE_SUCCESS = 'ENROLL_COURSE_SUCCESS'
export const ENROLL_COURSE_FAIL = 'ENROLL_COURSE_FAIL'

export const MY_LEARNER_REQUEST = 'MY_LEARNER_REQUEST'
export const MY_LEARNER_SUCCESS = 'MY_LEARNER_SUCCESST'
export const MY_LEARNER_FAIL = 'MY_LEARNER_FAIL'

export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST'
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS'
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL'

export const DELETE_COURSE_INFO = 'DELETE_COURSE_INFO'