export const MY_COURSE_REQUEST = 'MY_COURSE_REQUEST'
export const MY_COURSE_SUCCESS = 'MY_COURSE_SUCCESS'
export const MY_COURSE_FAIL = 'MY_COURSE_FAIL'

export const ADD_COURSE_REQUEST = 'ADD_COURSE_REQUEST'
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS'
export const ADD_COURSE_FAIL = 'ADD_COURSE_FAIL'