const dataNote = [
    {course: "Django Web Development: To-Do App", title: "How to set up Django", id: "1"},
    {course: "Network Administrator: Certified Wireless Network Administrator", title: "How to install Packet Tracer", id: "2"},
    {course: "Machine Learning Full Course: for PHP & Python Devs", title: "How to set up Python 3", id: "3"},
    {course: "Linux System Admin: Advance Linux System Administrator", title: "How to install Ubuntu", id: "4"},
    {course: "Javascript Full Course: Beginner to Expert", title: "How to set up Node.js", id: "5"},
    {course: "Gitting Started: Step-by-Step Git and Github Crash Course", title: "How to install Git Desktop", id: "6"},
    {course: "Django Web Development: To-Do App", title: "How to set up Django", id: "2"},
    {course: "Network Administrator: Certified Wireless Network Administrator", title: "How to install Packet Tracer", id: "1"},
    {course: "Machine Learning Full Course: for PHP & Python Devs", title: "How to set up Python 3", id: "4"},
    {course: "Linux System Admin: Advance Linux System Administrator", title: "How to install Ubuntu", id: "6"},
    {course: "Javascript Full Course: Beginner to Expert", title: "How to set up Node.js", id: "3"},
    {course: "Gitting Started: Step-by-Step Git and Github Crash Course", title: "How to install Git Desktop", id: "5"},
    {course: "Django Web Development: To-Do App", title: "How to set up Django", id: "1"},
    {course: "Network Administrator: Certified Wireless Network Administrator", title: "How to install Packet Tracer", id: "2"},
    {course: "Machine Learning Full Course: for PHP & Python Devs", title: "How to set up Python 3", id: "3"},
    {course: "Linux System Admin: Advance Linux System Administrator", title: "How to install Ubuntu", id: "4"},
    {course: "Javascript Full Course: Beginner to Expert", title: "How to set up Node.js", id: "5"},
    {course: "Gitting Started: Step-by-Step Git and Github Crash Course", title: "How to install Git Desktop", id: "6"},
    {course: "Django Web Development: To-Do App", title: "How to set up Django", id: "2"},
    {course: "Network Administrator: Certified Wireless Network Administrator", title: "How to install Packet Tracer", id: "1"},
    {course: "Machine Learning Full Course: for PHP & Python Devs", title: "How to set up Python 3", id: "4"},
    {course: "Linux System Admin: Advance Linux System Administrator", title: "How to install Ubuntu", id: "6"},
    {course: "Javascript Full Course: Beginner to Expert", title: "How to set up Node.js", id: "3"},
    {course: "Gitting Started: Step-by-Step Git and Github Crash Course", title: "How to install Git Desktop", id: "5"},
];
export default dataNote;