const dataQuiz = [
    {name: "Quiz 1: Introduction Django", course: "Django Web Development: To-Do App", length: "About 10 questions in 10 minute", id: "1"},
    {name: "Quiz 1: Introduction Network", course: "Network Administrator: Certified Wireless Network Administrator", length: "About 10 questions in 10 minute", id: "2"},
    {name: "Quiz 1: Introduction Machine Learning", course: "Machine Learning Full Course: for PHP & Python Devs", length: "About 10 questions in 10 minute", id: "3"},
    {name: "Quiz 1: Introduction Linux", course: "Linux System Admin: Advance Linux System Administrator", length: "About 10 questions in 10 minute", id: "4"},
    {name: "Quiz 1: Introduction Javascript", course: "Javascript Full Course: Beginner to Expert", length: "About 10 questions in 10 minute", id: "5"},
    {name: "Quiz 1: Introduction Git", course: "Gitting Started: Step-by-Step Git and Github Crash Course", length: "About 10 questions in 10 minute", id: "6"},
    {name: "Quiz 2: Introduction Django", course: "Django Web Development: To-Do App", length: "About 10 questions in 10 minute", id: "1"},
    {name: "Quiz 2: Introduction Network", course: "Network Administrator: Certified Wireless Network Administrator", length: "About 10 questions in 10 minute", id: "2"},
    {name: "Quiz 2: Introduction Machine Learning", course: "Machine Learning Full Course: for PHP & Python Devs", length: "About 10 questions in 10 minute", id: "3"},
    {name: "Quiz 2: Introduction Linux", course: "Linux System Admin: Advance Linux System Administrator", length: "About 10 questions in 10 minute", id: "4"},
    {name: "Quiz 2: Introduction Javascript", course: "Javascript Full Course: Beginner to Expert", length: "About 10 questions in 10 minute", id: "5"},
    {name: "Quiz 2: Introduction Git", course: "Gitting Started: Step-by-Step Git and Github Crash Course", length: "About 10 questions in 10 minute", id: "6"},
    {name: "Quiz 3: Introduction Django", course: "Django Web Development: To-Do App", length: "About 10 questions in 10 minute", id: "1"},
    {name: "Quiz 3: Introduction Network", course: "Network Administrator: Certified Wireless Network Administrator", length: "About 10 questions in 10 minute", id: "2"},
    {name: "Quiz 3: Introduction Machine Learning", course: "Machine Learning Full Course: for PHP & Python Devs", length: "About 10 questions in 10 minute", id: "3"},
    {name: "Quiz 3: Introduction Linux", course: "Linux System Admin: Advance Linux System Administrator", length: "About 10 questions in 10 minute", id: "4"},
    {name: "Quiz 3: Introduction Javascript", course: "Javascript Full Course: Beginner to Expert", length: "About 10 questions in 10 minute", id: "5"},
    {name: "Quiz 3: Introduction Git", course: "Gitting Started: Step-by-Step Git and Github Crash Course", length: "About 10 questions in 10 minute", id: "6"},
    {name: "Quiz 4: Introduction Django", course: "Django Web Development: To-Do App", length: "About 10 questions in 10 minute", id: "1"},
    {name: "Quiz 4: Introduction Network", course: "Network Administrator: Certified Wireless Network Administrator", length: "About 10 questions in 10 minute", id: "2"},
    {name: "Quiz 4: Introduction Machine Learning", course: "Machine Learning Full Course: for PHP & Python Devs", length: "About 10 questions in 10 minute", id: "3"},
    {name: "Quiz 4: Introduction Linux", course: "Linux System Admin: Advance Linux System Administrator", length: "About 10 questions in 10 minute", id: "4"},
    {name: "Quiz 4: Introduction Javascript", course: "Javascript Full Course: Beginner to Expert", length: "About 10 questions in 10 minute", id: "5"},
    {name: "Quiz 4: Introduction Git", course: "Gitting Started: Step-by-Step Git and Github Crash Course", length: "About 10 questions in 10 minute", id: "6"},
];
export default dataQuiz;